[project]
name = "toolstorepy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chromadb>=1.5.0",
    "requests>=2.32.5",
    "sentence-transformers>=5.2.2",
]

[project.scripts]
toolstorepy = "toolstorepy.cli:main"

